version: '3.5'

services: 
     example-backend:
          build: 
               context: ./example-backend
               dockerfile: Dockerfile
          ports: ["8080:8080"]
          command: "./server"
     example-frontend:
          build: 
               context: ./example-frontend
               dockerfile: Dockerfile
          ports: ["5000:5000"]
          command: ["serve", "-s", "-l", "5000", "build"]