version: '3.5'

services: 
     example-backend:
          build: ./example-backend
          environment: 
               REDIS_HOST: redis
               POSTGRES_HOST: postgres
          depends_on: [redis, postgres]    
          ports: ["8080:8080"]
          command: "./server"
     example-frontend:
          build: ./example-frontend
          ports: ["5000:5000"]
          command: ["serve", "-s", "-l", "5000", "build"]
     redis:
          container_name: rds
          image: redis
          restart: unless-stopped  
     postgres:
          container_name: postgres
          image: postgres
          environment:
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: postgres
               POSTGRES_DATABASE: postgres        
     nginx:
          container_name: nginx
          restart: unless-stopped
          image: nginx
          ports: ["80:80"]
          volumes: [./nginx.conf:/etc/nginx/nginx.conf]        